# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'ManualOverride'
        db.create_table(u'manual_override_manualoverride', (
            ('manual_override_id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('user_manual_override_id', self.gf('django.db.models.fields.BigIntegerField')(default=1)),
            ('manual_override_description', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('user_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('user_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['auth.User'])),
            ('blacklist_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('blacklist_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['users.BlackList'])),
            ('profile_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('profile_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['users.Profile'])),
            ('user_info_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('user_info_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['users.UserInfo'])),
            ('settings_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('settings_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['users.Settings'])),
            ('recommended_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('recommended_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['users.Recommended'])),
            ('forgot_password_request_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('forgot_password_request_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['users.ForgotPasswordRequest'])),
            ('user_functions_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('user_functions_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['users.UserFunctions'])),
            ('session_verification_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('session_verification_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['users.SessionVerification'])),
            ('stream_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('stream_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['stream.Stream'])),
            ('hashtag_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('hashtag_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['yap.Hashtag'])),
            ('channel_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('channel_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['yap.Channel'])),
            ('yap_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('yap_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['yap.Yap'])),
            ('reyap_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('reyap_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['yap.Reyap'])),
            ('like_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('like_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['yap.Like'])),
            ('listen_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('listen_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['yap.Listen'])),
            ('listen_click_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('listen_click_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['yap.ListenClick'])),
            ('follower_request_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('follower_request_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['yap.FollowerRequest'])),
            ('notification_type_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('notification_type_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['notification.NotificationType'])),
            ('notification_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('notification_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['notification.Notification'])),
            ('search_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('search_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['search.Search'])),
            ('report_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('report_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['report.Report'])),
            ('geographic_target_override_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('geographic_target_override_object', self.gf('django.db.models.fields.related.ForeignKey')(related_name='manual_overrides', to=orm['location.GeographicTarget'])),
            ('latitude', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('longitude', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('point', self.gf('django.contrib.gis.db.models.fields.PointField')(null=True, blank=True)),
            ('date_created', self.gf('django.db.models.fields.DateTimeField')(auto_now_add=True, blank=True)),
            ('is_active', self.gf('django.db.models.fields.BooleanField')(default=True)),
        ))
        db.send_create_signal(u'manual_override', ['ManualOverride'])


    def backwards(self, orm):
        # Deleting model 'ManualOverride'
        db.delete_table(u'manual_override_manualoverride')


    models = {
        u'auth.group': {
            'Meta': {'object_name': 'Group'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        u'auth.permission': {
            'Meta': {'ordering': "(u'content_type__app_label', u'content_type__model', u'codename')", 'unique_together': "((u'content_type', u'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['contenttypes.ContentType']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        u'auth.user': {
            'Meta': {'object_name': 'User'},
            'date_joined': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'blank': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "u'user_set'", 'blank': 'True', 'to': u"orm['auth.Group']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "u'user_set'", 'blank': 'True', 'to': u"orm['auth.Permission']"}),
            'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30'})
        },
        u'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        u'location.city': {
            'Meta': {'object_name': 'City'},
            'city_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'city_name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'country': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'city_country'", 'to': u"orm['location.Country']"}),
            'date_activated': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_deactivated': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'us_state': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'city_us_state'", 'null': 'True', 'to': u"orm['location.USState']"}),
            'us_zip_code': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'city_us_zip_code'", 'null': 'True', 'to': u"orm['location.USZIPCode']"})
        },
        u'location.country': {
            'Meta': {'object_name': 'Country'},
            'country_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'country_name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'date_activated': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_deactivated': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'location.geographictarget': {
            'Meta': {'object_name': 'GeographicTarget'},
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_deactivated': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'geographic_cities': ('django.db.models.fields.related.ManyToManyField', [], {'blank': 'True', 'related_name': "'geographic_cities'", 'null': 'True', 'symmetrical': 'False', 'to': u"orm['location.City']"}),
            'geographic_cities_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'geographic_countries': ('django.db.models.fields.related.ManyToManyField', [], {'blank': 'True', 'related_name': "'geographic_countries'", 'null': 'True', 'symmetrical': 'False', 'to': u"orm['location.Country']"}),
            'geographic_countries_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'geographic_states': ('django.db.models.fields.related.ManyToManyField', [], {'blank': 'True', 'related_name': "'geographic_states'", 'null': 'True', 'symmetrical': 'False', 'to': u"orm['location.USState']"}),
            'geographic_states_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'geographic_target_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'geographic_zip_codes': ('django.db.models.fields.related.ManyToManyField', [], {'blank': 'True', 'related_name': "'geographic_zip_codes'", 'null': 'True', 'symmetrical': 'False', 'to': u"orm['location.USZIPCode']"}),
            'geographic_zip_codes_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'location.usstate': {
            'Meta': {'object_name': 'USState'},
            'date_activated': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_deactivated': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'us_state_abbreviation': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'us_state_name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'us_states_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        u'location.uszipcode': {
            'Meta': {'object_name': 'USZIPCode'},
            'date_activated': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_deactivated': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'us_zip_code': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'us_zip_code_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        u'manual_override.manualoverride': {
            'Meta': {'ordering': "['-date_created']", 'object_name': 'ManualOverride'},
            'blacklist_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'blacklist_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['users.BlackList']"}),
            'channel_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'channel_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['yap.Channel']"}),
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'follower_request_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'follower_request_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['yap.FollowerRequest']"}),
            'forgot_password_request_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'forgot_password_request_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['users.ForgotPasswordRequest']"}),
            'geographic_target_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'geographic_target_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['location.GeographicTarget']"}),
            'hashtag_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'hashtag_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['yap.Hashtag']"}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'like_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'like_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['yap.Like']"}),
            'listen_click_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'listen_click_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['yap.ListenClick']"}),
            'listen_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'listen_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['yap.Listen']"}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'manual_override_description': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'manual_override_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'notification_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'notification_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['notification.Notification']"}),
            'notification_type_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'notification_type_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['notification.NotificationType']"}),
            'point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'profile_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'profile_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['users.Profile']"}),
            'recommended_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'recommended_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['users.Recommended']"}),
            'report_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'report_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['report.Report']"}),
            'reyap_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'reyap_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['yap.Reyap']"}),
            'search_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'search_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['search.Search']"}),
            'session_verification_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'session_verification_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['users.SessionVerification']"}),
            'settings_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'settings_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['users.Settings']"}),
            'stream_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'stream_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['stream.Stream']"}),
            'user_functions_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_functions_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['users.UserFunctions']"}),
            'user_info_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_info_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['users.UserInfo']"}),
            'user_manual_override_id': ('django.db.models.fields.BigIntegerField', [], {'default': '1'}),
            'user_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['auth.User']"}),
            'yap_override_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'yap_override_object': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'manual_overrides'", 'to': u"orm['yap.Yap']"})
        },
        u'notification.notification': {
            'Meta': {'ordering': "['-date_created']", 'object_name': 'Notification'},
            'acting_user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'notifications_sent'", 'to': u"orm['auth.User']"}),
            'created_follower_request': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'notifications'", 'null': 'True', 'to': u"orm['yap.FollowerRequest']"}),
            'created_follower_request_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'created_like': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'notifications'", 'null': 'True', 'to': u"orm['yap.Like']"}),
            'created_like_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'created_listen': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'notifications'", 'null': 'True', 'to': u"orm['yap.Listen']"}),
            'created_listen_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'created_reyap': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'notifications'", 'null': 'True', 'to': u"orm['yap.Reyap']"}),
            'created_reyap_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_user_deleted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_yapster_notification': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'notification_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'notification_type': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'notifications'", 'to': u"orm['notification.NotificationType']"}),
            'origin_reyap': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['yap.Reyap']", 'null': 'True', 'blank': 'True'}),
            'origin_reyap_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'origin_yap': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['yap.Yap']", 'null': 'True', 'blank': 'True'}),
            'origin_yap_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'notifications'", 'to': u"orm['auth.User']"}),
            'user_clicked_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'user_clicked_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_clicked_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_clicked_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_clicked_point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'user_notification_id': ('django.db.models.fields.BigIntegerField', [], {'default': '1'}),
            'user_read_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'user_read_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_read_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_read_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_read_point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'user_recommended_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_unrecommended_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_unverified_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_verified_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        u'notification.notificationtype': {
            'Meta': {'object_name': 'NotificationType'},
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_yapster_notification': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'notification_message': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'notification_name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '100'}),
            'notification_picture_path': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'notification_type_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        u'report.report': {
            'Meta': {'object_name': 'Report'},
            'contact_email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'null': 'True', 'blank': 'True'}),
            'contact_phone_number': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'datetime_reported': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True', 'blank': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_user_deleted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'report_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'reported_bug_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'reported_general_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'reported_reyap': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'reports'", 'null': 'True', 'to': u"orm['yap.Reyap']"}),
            'reported_reyap_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'reported_user': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'reports'", 'null': 'True', 'to': u"orm['auth.User']"}),
            'reported_user_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'reported_yap': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'reports'", 'null': 'True', 'to': u"orm['yap.Yap']"}),
            'reported_yap_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'reported'", 'to': u"orm['auth.User']"}),
            'user_report_id': ('django.db.models.fields.BigIntegerField', [], {'default': '1'})
        },
        u'search.search': {
            'Meta': {'ordering': "['-date_searched']", 'object_name': 'Search'},
            'channels_searched': ('django.db.models.fields.related.ManyToManyField', [], {'blank': 'True', 'related_name': "'in_searches'", 'null': 'True', 'symmetrical': 'False', 'to': u"orm['yap.Channel']"}),
            'channels_searched_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'date_searched': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'explore_searched_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'general_searched_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'hashtags_searched': ('django.db.models.fields.related.ManyToManyField', [], {'blank': 'True', 'related_name': "'in_searches'", 'null': 'True', 'symmetrical': 'False', 'to': u"orm['yap.Hashtag']"}),
            'hashtags_searched_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_after_request': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_people': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_recent': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_trending': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'profile_likes_stream_searched_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'profile_listens_stream_searched_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'profile_posts_stream_searched_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'profile_searched': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['auth.User']", 'null': 'True', 'blank': 'True'}),
            'profile_searched_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'search_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'stream_searched_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'text_searched': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'user_handles_searched': ('django.db.models.fields.related.ManyToManyField', [], {'blank': 'True', 'related_name': "'in_searches'", 'null': 'True', 'symmetrical': 'False', 'to': u"orm['auth.User']"}),
            'user_handles_searched_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_search_id': ('django.db.models.fields.BigIntegerField', [], {'default': '1'}),
            'user_searching': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'searches'", 'to': u"orm['auth.User']"}),
            'yap_searched_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        u'stream.stream': {
            'Meta': {'ordering': "['-date_created']", 'object_name': 'Stream'},
            'date_created': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_user_deleted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'post_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'reyap': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'stream'", 'null': 'True', 'to': u"orm['yap.Reyap']"}),
            'reyap_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'stream'", 'to': u"orm['auth.User']"}),
            'user_post_id': ('django.db.models.fields.BigIntegerField', [], {'blank': 'True'}),
            'user_posted': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'posted_to'", 'null': 'True', 'to': u"orm['auth.User']"}),
            'yap': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'stream'", 'to': u"orm['yap.Yap']"})
        },
        u'users.blacklist': {
            'Meta': {'object_name': 'BlackList'},
            'account_created_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'account_created_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'blacklist_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'blacklisted_date': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'})
        },
        u'users.forgotpasswordrequest': {
            'Meta': {'ordering': "['-date_created']", 'object_name': 'ForgotPasswordRequest'},
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_signed_in_without_using': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'date_used': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'forgot_password_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'forgot_password_request_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'forgot_password_request_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'forgot_password_request_point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'reset_password_security_code': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True', 'blank': 'True'}),
            'reset_password_security_code_used_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'forgot_password_requests'", 'to': u"orm['auth.User']"}),
            'user_email': ('django.db.models.fields.EmailField', [], {'max_length': '75'}),
            'user_forgot_password_id': ('django.db.models.fields.BigIntegerField', [], {'default': '1'}),
            'user_signed_in_after_without_using_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        u'users.profile': {
            'Meta': {'object_name': 'Profile'},
            'date_of_birth': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'follower_count': ('django.db.models.fields.BigIntegerField', [], {'default': '0'}),
            'following_count': ('django.db.models.fields.BigIntegerField', [], {'default': '0'}),
            'gender': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'high_security_account_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_user_deleted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'like_count': ('django.db.models.fields.BigIntegerField', [], {'default': '0'}),
            'listen_count': ('django.db.models.fields.BigIntegerField', [], {'default': '0'}),
            'listen_stream_public': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'phone_number': ('django.db.models.fields.CharField', [], {'max_length': '20', 'blank': 'True'}),
            'posts_are_private': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'profile_picture_cropped_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'profile_picture_cropped_path': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'profile_picture_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'profile_picture_path': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'reyap_count': ('django.db.models.fields.BigIntegerField', [], {'default': '0'}),
            'user': ('django.db.models.fields.related.OneToOneField', [], {'related_name': "'profile'", 'unique': 'True', 'primary_key': 'True', 'to': u"orm['auth.User']"}),
            'user_city': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'profile_user_city'", 'null': 'True', 'to': u"orm['location.City']"}),
            'user_country': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'profile_user_country'", 'null': 'True', 'to': u"orm['location.Country']"}),
            'user_us_state': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'profile_user_state'", 'null': 'True', 'to': u"orm['location.USState']"}),
            'user_us_zip_code': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'profile_user_zip_code'", 'null': 'True', 'to': u"orm['location.USZIPCode']"}),
            'verified_account_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'yap_count': ('django.db.models.fields.BigIntegerField', [], {'default': '0'})
        },
        u'users.recommended': {
            'Meta': {'object_name': 'Recommended'},
            'date_deactivated': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'date_recommended': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_will_be_deactivated': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'geographic_target': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['location.GeographicTarget']", 'null': 'True', 'blank': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_user_deleted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'recommendation_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'recommended'", 'to': u"orm['auth.User']"}),
            'user_recommendation_id': ('django.db.models.fields.BigIntegerField', [], {'default': '1'})
        },
        u'users.sessionverification': {
            'Meta': {'object_name': 'SessionVerification'},
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'session_created_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'session_created_point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'session_device_token': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True', 'blank': 'True'}),
            'session_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'session_logged_out_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'session_manually_closed_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'session_timed_out_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'sesssion_created_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'sessions'", 'to': u"orm['auth.User']"}),
            'user_session_id': ('django.db.models.fields.BigIntegerField', [], {'default': '1'})
        },
        u'users.settings': {
            'Meta': {'object_name': 'Settings'},
            'facebook_account_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'facebook_connection_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'facebook_share_reyap': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'google_plus_account_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'google_plus_connection_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'google_plus_share_reyap': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_user_deleted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'linkedin_account_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'linkedin_connection_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'linkedin_share_reyap': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'notify_for_likes': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'notify_for_listens': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'notify_for_mentions': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'notify_for_new_followers': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'notify_for_reyaps': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'notify_for_yapster': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'twitter_account_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'twitter_connection_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'twitter_share_reyap': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user': ('django.db.models.fields.related.OneToOneField', [], {'related_name': "'settings'", 'unique': 'True', 'primary_key': 'True', 'to': u"orm['auth.User']"})
        },
        u'users.userfunctions': {
            'Meta': {'object_name': 'UserFunctions'},
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_user_deleted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user': ('django.db.models.fields.related.OneToOneField', [], {'related_name': "'functions'", 'unique': 'True', 'primary_key': 'True', 'to': u"orm['auth.User']"})
        },
        u'users.userinfo': {
            'Meta': {'object_name': 'UserInfo'},
            'date_of_birth': ('django.db.models.fields.DateField', [], {}),
            'description': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75'}),
            'facebook_account_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'facebook_connection_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'facebook_share_reyap': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'gender': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'google_plus_account_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'google_plus_connection_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'google_plus_share_reyap': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'high_security_account_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_user_deleted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_account_modified_date': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'linkedin_account_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'linkedin_connection_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'linkedin_share_reyap': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'listen_stream_public': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'notify_for_likes': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'notify_for_mentions': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'notify_for_new_followers': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'notify_for_reyaps': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'notify_for_yapster': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'phone_number': ('django.db.models.fields.CharField', [], {'max_length': '20', 'blank': 'True'}),
            'posts_are_private': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'profile_picture_cropped_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'profile_picture_cropped_path': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'profile_picture_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'profile_picture_path': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'twitter_account_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'twitter_connection_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'twitter_share_reyap': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'user_city': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'user_city'", 'null': 'True', 'to': u"orm['location.City']"}),
            'user_country': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'user_country'", 'null': 'True', 'to': u"orm['location.Country']"}),
            'user_created_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_created_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'user_created_point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'user_deleted_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'user_id': ('django.db.models.fields.BigIntegerField', [], {'primary_key': 'True'}),
            'user_us_state': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'user_state'", 'null': 'True', 'to': u"orm['location.USState']"}),
            'user_us_zip_code': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'user_zip_code'", 'null': 'True', 'to': u"orm['location.USZIPCode']"}),
            'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30'}),
            'verified_account_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        u'yap.channel': {
            'Meta': {'object_name': 'Channel'},
            'channel_description': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'channel_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'channel_name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_deactivated': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'geographic_target': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['location.GeographicTarget']", 'null': 'True', 'blank': 'True'}),
            'icon_explore_path_clicked': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'icon_explore_path_unclicked': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'icon_yap_path_clicked': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'icon_yap_path_unclicked': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_bonus_channel': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_promoted': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'yap.followerrequest': {
            'Meta': {'ordering': "['-date_created']", 'object_name': 'FollowerRequest'},
            'accepted_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'accepted_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'accepted_point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'created_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'created_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'created_point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'date_accepted': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_denied': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'date_unfollowed': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'date_unrequested': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'denied_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'denied_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'denied_point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'follower_request_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_accepted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_denied': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_unfollowed': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_unrequested': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_user_deleted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'unfollowed_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'unfollwed_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'unfollwed_point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'unrequested_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'unrequested_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'unrequested_point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'requests'", 'to': u"orm['auth.User']"}),
            'user_follower_request_id': ('django.db.models.fields.BigIntegerField', [], {'default': '1'}),
            'user_requested': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'requested'", 'to': u"orm['auth.User']"})
        },
        u'yap.hashtag': {
            'Meta': {'object_name': 'Hashtag'},
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'hashtag_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'hashtag_name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_blocked': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        u'yap.like': {
            'Meta': {'ordering': "['-date_created']", 'object_name': 'Like'},
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_unliked': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_user_deleted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'like_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'reyap': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'likes'", 'null': 'True', 'to': u"orm['yap.Reyap']"}),
            'reyap_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'unliked_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'unliked_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'unliked_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'unliked_point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'likes'", 'to': u"orm['auth.User']"}),
            'user_like_id': ('django.db.models.fields.BigIntegerField', [], {'default': '1'}),
            'yap': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'likes'", 'to': u"orm['yap.Yap']"})
        },
        u'yap.listen': {
            'Meta': {'ordering': "['-date_created']", 'object_name': 'Listen'},
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_user_deleted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'listen_click_count': ('django.db.models.fields.BigIntegerField', [], {'default': '0'}),
            'listen_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'reyap': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'listens'", 'null': 'True', 'to': u"orm['yap.Reyap']"}),
            'reyap_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'time_listened': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'listens'", 'to': u"orm['auth.User']"}),
            'user_listen_id': ('django.db.models.fields.BigIntegerField', [], {'default': '1'}),
            'yap': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'listens'", 'to': u"orm['yap.Yap']"})
        },
        u'yap.listenclick': {
            'Meta': {'ordering': "['-date_created']", 'object_name': 'ListenClick'},
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'hashtag_clicked': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'listen_clicked'", 'null': 'True', 'to': u"orm['yap.Hashtag']"}),
            'hashtag_clicked_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_user_deleted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'liked_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'liked_like': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'listens_liked'", 'null': 'True', 'to': u"orm['yap.Like']"}),
            'listen': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'listen_clicked'", 'to': u"orm['yap.Listen']"}),
            'listen_click_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'picture_clicked_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'reyapped_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'reyapped_reyap': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'listens_reyapped'", 'null': 'True', 'to': u"orm['yap.Reyap']"}),
            'skipped_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'time_clicked': ('django.db.models.fields.BigIntegerField', [], {}),
            'unliked_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'unreyapped_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'user_listen_clicked'", 'to': u"orm['auth.User']"}),
            'user_handle_clicked': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'listen_handle_clicked'", 'null': 'True', 'to': u"orm['auth.User']"}),
            'user_handle_clicked_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_listen_click_id': ('django.db.models.fields.BigIntegerField', [], {'default': '1'}),
            'user_reyapped_clicked_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_yapped_clicked_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'web_link_clicked_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        u'yap.reyap': {
            'Meta': {'ordering': "['-date_created']", 'object_name': 'Reyap'},
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'deleted_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'deleted_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'deleted_point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'facebook_account_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'facebook_connection_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'google_plus_account_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'google_plus_connection_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_unreyapped': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_user_deleted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'like_count': ('django.db.models.fields.BigIntegerField', [], {'default': '0'}),
            'linkedin_account_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'linkedin_connection_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'listen_count': ('django.db.models.fields.BigIntegerField', [], {'default': '0'}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'reyap_count': ('django.db.models.fields.BigIntegerField', [], {'default': '0'}),
            'reyap_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'reyap_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'reyap_reyap': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'reyaps'", 'null': 'True', 'to': u"orm['yap.Reyap']"}),
            'twitter_account_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'twitter_connection_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'unreyapped_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'unreyapped_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'unreyapped_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'unreyapped_point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'reyaps'", 'to': u"orm['auth.User']"}),
            'user_reyap_id': ('django.db.models.fields.BigIntegerField', [], {'default': '1'}),
            'yap': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'reyaps'", 'to': u"orm['yap.Yap']"})
        },
        u'yap.yap': {
            'Meta': {'ordering': "['-date_created']", 'object_name': 'Yap'},
            'audio_path': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'channel': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'yaps'", 'null': 'True', 'to': u"orm['yap.Channel']"}),
            'channel_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'deleted_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'deleted_latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'deleted_longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'deleted_point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'facebook_account_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'facebook_shared_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'google_plus_account_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'google_plus_shared_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'hashtags': ('django.db.models.fields.related.ManyToManyField', [], {'blank': 'True', 'related_name': "'yaps'", 'null': 'True', 'symmetrical': 'False', 'to': u"orm['yap.Hashtag']"}),
            'hashtags_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_private': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_user_deleted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'length': ('django.db.models.fields.BigIntegerField', [], {}),
            'like_count': ('django.db.models.fields.BigIntegerField', [], {'default': '0'}),
            'linkedin_account_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'linkedin_shared_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'listen_count': ('django.db.models.fields.BigIntegerField', [], {'default': '0'}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'picture_cropped_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'picture_cropped_path': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'picture_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'picture_path': ('django.db.models.fields.CharField', [], {'max_length': '255', 'unique': 'True', 'null': 'True', 'blank': 'True'}),
            'point': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True', 'blank': 'True'}),
            'reyap_count': ('django.db.models.fields.BigIntegerField', [], {'default': '0'}),
            'title': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'twitter_account_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'twitter_shared_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'yaps'", 'to': u"orm['auth.User']"}),
            'user_tags': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'yaps_in'", 'symmetrical': 'False', 'to': u"orm['auth.User']"}),
            'user_tags_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_yap_id': ('django.db.models.fields.BigIntegerField', [], {'default': '1'}),
            'web_link': ('django.db.models.fields.URLField', [], {'max_length': '255', 'null': 'True', 'blank': 'True'}),
            'web_link_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'yap_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        }
    }

    complete_apps = ['manual_override']